env:
  commonjs: true
  es6: true
  node: true
extends: google
parserOptions:
  ecmaVersion: 2018
rules:
  linebreak-style: ["error", "windows"]
  object-curly-spacing: ["error", "always"]
  indent: [2, 2]
  max-len:
    - error
    - code: 100
  require-jsdoc:
    - off
